{% set name = "pyscope" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WWGolay/pyscope/archive/v{{ version }}.tar.gz
  sha256: 2ee8eb2d7bcca22e916730c797a7fbe407dd465c804e41418e6c7be970ec71e5

build:
  skip: true  # [py<310]
  entry_points:
    - init-telrun-dir = pyscope.telrun.init_dirs:init_telrun_dir_cli
    - init-remote-dir = pyscope.telrun.init_dirs:init_remote_dir_cli
    - schedtel = pyscope.telrun.schedtel:schedtel_cli
    - plot-schedule-gantt = pyscope.telrun.schedtel:plot_schedule_gantt_cli
    - start-telrun = pyscope.telrun.startup:start_telrun_cli
    - start-syncfiles = pyscope.telrun.startup:start_syncfiles_cli
    - syncfiles = pyscope.telrun.syncfiles:syncfiles_cli
    - calc-zmag = pyscope.analysis.calc_zmag:calc_zmag_cli
    - collect-calibration-set = pyscope.observatory.collect_calibration_set:collect_calibration_set_cli
    - avg-fits = pyscope.reduction.avg_fits:avg_fits_cli
    - calib-images = pyscope.reduction.calib_images:calib_images_cli
    - ccd-calib = pyscope.reduction.ccd_calib:ccd_calib_cli
    - fitslist = pyscope.reduction.fitslist:fitslist_cli
    - exoplanet-transits = pyscope.telrun.exoplanet_transits:exoplanet_transits_cli
    - mk-mosaic-schedule = pyscope.telrun.mk_mosaic_schedule:mk_mosaic_schedule_cli
    - rst = pyscope.telrun.rst:rst_cli
    - summary-report = pyscope.telrun.summary_report:summary_report_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=42.0
    - wheel
    - pip
  run:
    - python
    - astroplan >=0.9
    - astropy >=5.3.1
    - astroquery >=0.4.6
    - astroscrappy >=1.1.0
    - click >=8.1.6
    - cmcrameri >=1.4.0
    - markdown >=3.4.4
    - matplotlib-base >=3.5.1
    - numpy >=1.24.4
    - paramiko >=3.3.1
    - photutils >=1.7.0
    - prettytable >=3.8.0
    - pywin32-on-windows >=304  # [win]
    - smplotlib >=0.0.6
    - timezonefinder >=6.0.2
    - tksheet >=6.2.3
    - tqdm >=4.66.1

test:
  imports:
    - pyscope
  commands:
    - pip check
    - init-telrun-dir --help
    - init-remote-dir --help
    - schedtel --help
    - plot-schedule-gantt --help
    - start-telrun --help
    - start-syncfiles --help
    - syncfiles --help
    - calc-zmag --help
    - collect-calibration-set --help
    - avg-fits --help
    - calib-images --help
    - ccd-calib --help
    - fitslist --help
    - exoplanet-transits --help
    - mk-mosaic-schedule --help
    - rst --help
    - summary-report --help
  requires:
    - pip

about:
  home: https://github.com/WWGolay/pyscope
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wgolay30
